ext_if="wlan0"

# set skip on lo
table <cni-nat> 

# NAT (optional; comment out for testing inbound SSH)
nat on $ext_if inet from !($ext_if) -> ($ext_if)

nat-anchor "cni-rdr/*"
rdr-anchor "cni-rdr/*"


block in all
pass on lo0 all
# Allow inbound TCP services
pass in inet proto tcp to any port { 22 80 443 8000 8080 } flags S/SA keep state
pass in inet proto udp to port { 53 } 

# Allow DHCP (client)
pass in  inet proto udp from port 68 to port 67 keep state
# pass out inet proto udp from port 68 to port 67 keep state
 
# Allow ICMP
pass inet proto icmp all keep state

# Allow all outbound
pass out all keep state
