#!/usr/bin/env python3

import os
import sys
import requests as r

from app2.helpers import jail_attach, get_jail_id_by_name

if __name__ == '__main__':
    if len(sys.argv)<3:
        print("Usage: python exec.py <jail_name> <executable> <args>")
        exit(1)

    jail_name =    sys.argv[1]
    executable = sys.argv[2]
    res = r.get(f'http://localhost:5000/api/container/{jail_name}')

    if res.status_code!=200:
        print(res.content)
        exit(1)

    data = res.json()
    if(data.get('status') != 'running'):
        print('Container is not running')
        exit(-1)    
    res = jail_attach(jail_name)
    if(res < 0):
        print('Failed to exec into container')
        exit(-1)
    
    os.chdir(data.get('workingDir', '/'))
    env = data.get('env', {})
    env.setdefault('USER', data.get('user', 'root'))
    env.setdefault('HOSTNAME', jail_name+'.jail')
    env.setdefault('HOME', '/root')
    env.setdefault('SHELL', '/bin/tcsh')
    env.setdefault('TERM', 'xterm')
    env.setdefault('PS1',"\\u@\\h:\\w $ ")


    try:
        os.execvpe(executable, sys.argv[2:], env)
    except FileNotFoundError as e:
        print(f'OCI Error: {e.strerror}: {e.filename.decode()!r}' )
    